### ISSUE TITLE
[Q] Can I replace .htaccess rewrite rules with CustomRequest?

### ISSUE THREAD

**Issue by zaigham** [Jako/CustomRequest#1]
If Yes, how can I translate the following rule into CustomRequest config:

```
RewriteCond %{REQUEST_URI} /browse/(.+?)$ [NC]
RewriteRule (.*) /?p=%1$ [L,QSA,NC]
```

Currently, if I use http://domain.tld/browse/2 , it returns to same page and utilize getPage for pagination.

Thanks!

**Comment by Jako** [comment]
At the moment only one resource could be targeted with one CustomRequest config.

In your case the following config could be the thing:

``` php
$settings['browse'] = array(
    'alias' => 'browse/',
    'urlParams' => array('p')
);
```

**Comment by Jako** [comment]
With CustomRequest 1.2.x you could replace rewrite rules. See the Pagination example on http://jako.github.io/CustomRequest/usage/#pagination
