### ISSUE TITLE
Are dynamic parameter key names possible?

### ISSUE THREAD

**Issue by davidpede** [Jako/CustomRequest#11]
I have a resource url like: `https://my.test/shop/books/fiction/`

I've setup a config with only: Config > Alias Path: `#.*?books/.*?(filters/)#` filled in.

If I load: `https://my.test/shop/books/fiction/filters/key1/value1/key2/value2/foo/bar/` the parameters array returned is formatted like:
```
[p1] => key1,
[p2] => value1
[p3] => key2
[p4] => value2
[p5] => foo
[p6] => bar
```
Is there anyway to assign dynamic key names to the array instead? I'm needing:
```
[key1] => value1
[key2] => value2
[foo] => bar
```
I've tried loads of regex's but can't seem to get it - not sure if possible?

**Comment by Jako** [comment]
The problem is to detect which property is a key and which is a value. That could maybe done with some nested regular expression.

I would iterate over the keys and take the uneven values as key and the even ones as a value.
