### ISSUE TITLE
tvSuperSelect : tags 

### ISSUE THREAD

**Issue by TITAN-UZ** [Jako/CustomRequest#17]
Hi! Jako
Please help me to settings CustomRequest for tvSuperSelect create an url

https://site.com/tags/?tag=Apple  to https://site.com/tags/Apple

https://site.com/tags/?page=2&tag=Apple Apple to https://site.com/tags/Apple/page/2

**Comment by Jako** [comment]
Please try the following (not tested):

You have to create 2 rules:
- the first one would detect `/tags/Apple/page/2` in the URL with a regular expression 
(Alias Path `#.*?(/tags/(.*?)/page/(.*?))#` and URI Parameter `["unused","tag","page"]`)
- the second one would detect `/tags/Apple` in the URL with a regular expression
(Alias Path `#.*?(/page/(.*?))#` and URI Parameter `["unused","page"]`)

The first subpattern in the regular expression is stripped from the url, so I use this to strip the url and map it to the unused URI Parameter. I hope this works - please tell me.

The first one has to be executed first (has to occur first in the grid), then the second one will not be executed.
