### ISSUE TITLE
How to go about having a wildcard child page?

### ISSUE THREAD

**Issue by wshawn** [Jako/CustomRequest#37]
I have a section with almost 1200 languages.  The structure is siteroot/directory1/languages/language. How would I go about having the language page be the landing for each language: e.g., siteroot/directory1/languages/english, siteroot/directory1/languages/spanish?

I've tried different options and not quite getting there.

Site is on MODX 3.0.1.

**Comment by Jako** [comment]
I don't get it. What should be the target resource? What are the parts to detect in the url?

**Comment by wshawn** [comment]
The target resource would land on the Language resource. The detect string would be anything after directory1/languages/

**Comment by Jako** [comment]
How many different 'language' folders do you have? Can a language resource be the target? Then you need a resource for english, spanish etc. and for each target language you need one rule.

CustomRequest needs a target resource in most cases. In the case that you use a regular expression for retrieving i.e. a page number, the remaining part of the url is used as the target. I am not sure if that part can be at the end of the url.

**Comment by wshawn** [comment]
I have a languages (which lists available languages) with a child of language. I was thinking of having the child represent each language dynamically.

**Comment by Jako** [comment]
> The target resource would land on the Language resource.

Do you mean 'Languages' resource then? Then it is easy: Create a rule that uses the Languages resource as target and the alias path of that resource is shown in green in the configuration. If you set the URI Parameter to `["language"]`, the not found URI `directory1/languages/english.html` is forwarded to the target resource with the request property `language = "english"`.

Or did I get you wrong?
