### ISSUE TITLE
Bugs in CustomRequest.php

### ISSUE THREAD

**Issue by iicuken** [Jako/CustomRequest#40]
--- a/html/core/components/customrequest/src/CustomRequest.php  Sat Apr 08 10:57:15 2023 +0300
+++ b/html/core/components/customrequest/src/CustomRequest.php  Mon Apr 10 10:55:38 2023 +0300
@@ -185,19 +185,18 @@
                     if (!$resourceId) {
                         $resourceId = 0;
                         if (!$this->isRegularExpression($alias)) {
                             $resourceId = $this->modx->findResource($alias);
                             if (!$resourceId) {
                                 // If resourceId could not be calculated and alias is not a valid regular expression, don't use that setting
                                 if ($this->getOption('debug')) {
                                     $this->modx->log(xPDO::LOG_LEVEL_ERROR, 'Could not calculate the resourceId for the given alias "' . $alias . '".', '', 'CustomRequest Plugin');
                                 }
-                                break;
                             }
                         } else {
                             $aliasRegEx = true;
                         }
                     }
                     if ($resourceId) {
                         $resource = $this->modx->getObject('modResource', $resourceId);
                         if ($resource) {
                             $contextKey = $resource->get('context_key');

### Here: it should be no break on resource id  not found for alias - other good aliases will be thrown away, i think it should be continue;
@@ -278,19 +277,19 @@
             $search = substr($search, strlen($this->modx->cultureKey) + 1);
         }
 
         $valid = false;
         // Loop through the allowed aliases
         if (is_array($this->requests) && count($this->requests)) {
             foreach ($this->requests as $request) {
                 if (!$request['aliasRegEx']) {
                     // Check if searched string starts with the alias and for the contextKey
-                    if ($request['alias'] && 0 === strpos($search, $request['alias']) && $request['contextKey'] == $this->modx->context->key) {
+                    if ($request['alias'] && $search === $request['alias'] && $request['contextKey'] == $this->modx->context->key) {
                         $this->found = [

### Here:  0 === strpos($search, $request['alias'])  for alias "school/lession"  will find resource with alias "school" if it goes  before  alias "school/lession" in reqests cache.

**Comment by Jako** [comment]
Please create a pull request with this. I don't see what you want to change the way you have posted the issue above.
