### ISSUE TITLE
wrong table prefix 

### ISSUE THREAD

**Issue by V0IDNIL** [Jako/CustomRequest#6]
MODX Revolution 2.4.2-pl
CustomRequest 1.2.1-pl

The sql table prefix for my modx installation is modxfc_ instead of modx_
When installing CustomRequest it installs the table under modx_customrequest_configs though.

**Comment by Jako** [comment]
Yes, that is a bug in Git-Package-Management.

**Comment by Jako** [comment]
Fixed with 1.2.2
